import { Language } from './types';

export const TRANSLATIONS = {
  [Language.ENGLISH]: {
    app_name: "Job_path",
    dashboard: "Dashboard",
    resume_builder: "Resume Builder",
    job_match: "Career Path",
    mock_interview: "Mock Interview",
    welcome: "Welcome,",
    interview_score: "Latest Score",
    skills_tracked: "Skills Identified",
    resume_strength: "Resume Strength",
    start_interview: "Start New Interview",
    edit_resume: "Edit Resume",
    personal_info: "Personal Information",
    upload_photo: "Upload Photo",
    remove_photo: "Remove",
    experience: "Experience",
    skills: "Skills",
    languages: "Languages",
    education: "Education",
    ai_enhance: "AI Enhance",
    save: "Save",
    analyze_profile: "Analyze Profile for Jobs",
    recommended_jobs: "Recommended Jobs",
    match: "Match",
    missing_skills: "Missing Skills",
    start_practice: "Practice This",
    interview_setup: "Interview Setup",
    select_type: "Select Interview Type",
    start_session: "Start Session",
    end_session: "End Session",
    listening: "Listening...",
    speaking: "Speaking...",
    type_message: "Type your answer...",
    send: "Send",
    feedback: "Interview Feedback",
    strengths: "Strengths",
    weaknesses: "Weaknesses",
    tips: "Improvement Tips",
    editor: "Editor",
    preview: "Preview & Export",
    download_pdf: "Download PDF",
    template_professional: "Professional",
    template_modern: "Modern",
    template_creative: "Creative",
    empty_dashboard: "Your dashboard is empty. Start by building your resume!",
    create_resume_btn: "Create Resume",
    add_experience: "Add Experience",
    summary_placeholder: "Brief professional summary...",
    role_placeholder: "Job Title",
    company_placeholder: "Company Name",
    duration_placeholder: "e.g. 2020 - Present",
    reset_data: "Reset App Data",
    reset_confirm_title: "Delete all data?",
    reset_confirm_desc: "This will permanently delete your resume, interview history, and progress. This action cannot be undone.",
    cancel: "Cancel",
    confirm_delete: "Delete Everything",
    recent_interviews: "Recent Interviews",
    view_details: "View Details",
    no_interviews: "No interviews yet. Start one to practice!",
    date: "Date"
  },
  [Language.ARABIC]: {
    app_name: "Job_path",
    dashboard: "لوحة التحكم",
    resume_builder: "صانع السيرة الذاتية",
    job_match: "المسار الوظيفي",
    mock_interview: "المقابلة الذكية",
    welcome: "مرحباً،",
    interview_score: "آخر نتيجة",
    skills_tracked: "المهارات المكتشفة",
    resume_strength: "قوة السيرة الذاتية",
    start_interview: "ابدأ مقابلة",
    edit_resume: "تعديل السيرة الذاتية",
    personal_info: "المعلومات الشخصية",
    upload_photo: "رفع صورة",
    remove_photo: "حذف",
    experience: "الخبرة العملية",
    skills: "المهارات",
    languages: "اللغات",
    education: "التعليم",
    ai_enhance: "تحسين بالذكاء الاصطناعي",
    save: "حفظ",
    analyze_profile: "تحليل الملف",
    recommended_jobs: "الوظائف المقترحة",
    match: "تطابق",
    missing_skills: "مهارات ناقصة",
    start_practice: "تدرب الآن",
    interview_setup: "إعداد المقابلة",
    select_type: "نوع المقابلة",
    start_session: "بدء الجلسة",
    end_session: "إنهاء",
    listening: "جاري الاستماع...",
    speaking: "جاري التحدث...",
    type_message: "اكتب إجابتك...",
    send: "إرسال",
    feedback: "التقييم",
    strengths: "نقاط القوة",
    weaknesses: "نقاط الضعف",
    tips: "نصائح",
    editor: "المحرر",
    preview: "معاينة وتصدير",
    download_pdf: "تحميل PDF",
    template_professional: "احترافي",
    template_modern: "عصري",
    template_creative: "إبداعي",
    empty_dashboard: "لوحة التحكم فارغة. ابدأ بإنشاء سيرتك الذاتية!",
    create_resume_btn: "إنشاء سيرة ذاتية",
    add_experience: "إضافة خبرة",
    summary_placeholder: "ملخص مهني مختصر...",
    role_placeholder: "المسمى الوظيفي",
    company_placeholder: "اسم الشركة",
    duration_placeholder: "مثال: 2020 - الآن",
    reset_data: "تصفير البيانات",
    reset_confirm_title: "حذف جميع البيانات؟",
    reset_confirm_desc: "سيؤدي هذا إلى حذف السيرة الذاتية وسجل المقابلات وكل تقدمك بشكل دائم. لا يمكن التراجع عن هذا الإجراء.",
    cancel: "إلغاء",
    confirm_delete: "حذف الكل",
    recent_interviews: "المقابلات الأخيرة",
    view_details: "عرض التفاصيل",
    no_interviews: "لا توجد مقابلات بعد. ابدأ واحدة للتدريب!",
    date: "التاريخ"
  }
};

export const INITIAL_PROFILE = {
  name: "",
  email: "",
  phone: "",
  summary: "",
  skills: [],
  languages: [],
  experience: [],
  education: "",
  targetRole: "",
  interviewHistory: []
};